"""Initial

Revision ID: 3c3a1d2559b6
Revises:
Create Date: 2024-09-11 09:29:14.123203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c3a1d2559b6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("metadata_url", sa.String(length=500), nullable=True),
        sa.Column(
            "visibility",
            sa.Enum("PUBLIC", "INTERNAL", name="visibility"),
            nullable=False,
        ),
        sa.Column(
            "domain",
            sa.Enum("EDW", "DATA_DOT_GOV", "FS_GEODATA", "CRV", name="domains"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("metadata_url"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "keyword",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assetkeyword",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.id"],
        ),
        sa.PrimaryKeyConstraint("asset_id", "keyword_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("assetkeyword")
    op.drop_table("keyword")
    op.drop_table("asset")
    # ### end Alembic commands ###
